config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
    confirmations: "users/confirmations",
    unlocks: "users/unlocks"
  }

  get "up" => "rails/health#show", :as => :rails_health_check

  namespace :admin do
    root "pages#index"

    resources :users, only: %i[index create update]
  end

  root "home#index"

  ###############
  ###   API22  ###
  ###############

  namespace :api do
  end
end

app/models/user.rb
class User < ApplicationRecord
  include StatusDetailManageable
  include Countable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :email, format: {with: URI::MailTo::EMAIL_REGEXP}
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  include AdminCountable
  include Pagy::Backend

  layout "admin"
  before_action :get_user, only: %i[update]

  def index
    @pagy, @users = pagy(User.all.order(:name))

    if params[:query].present?
      @users = @users.search_global(params[:query])
    end

    @user = User.new
  end

  def create
    user = User.new(user_params)

    if user.save
      render turbo_stream: turbo_stream.action(:redirect, admin_users_path)
    else
      render turbo_stream: turbo_stream.replace("form_user", partial: "admin/users/form", locals: {user: @user})
    end
  end

  def update
    if @user.update(user_params)
      render turbo_stream: turbo_stream.action(:redirect, admin_users_path)
    else
      render turbo_stream: turbo_stream.replace("form_user", partial: "admin/users/form", locals: {user: @user})
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :role,
      :image
    )
  end

  def get_user
    @user = User.find(params[:id])
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    if params[:user].present?
      user = User.find_by(email: params[:user][:email])

      if user.present? && user.valid_password?(params[:user][:password])
        sign_in(user)
        redirect_to admin_root_path
      else
        redirect_to user_session_path
      end
    else
      super
    end
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    sign_out current_user
    redirect_to user_session_path, notice: "Signed out successfully."
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= turbo_frame_tag "form_user" do %>
  <%= form_with model: user, url: user.persisted? ? admin_user_path(user) : admin_users_path do |f| %>
    <section class="h-100 m-5 gap-5">
      <section class="grid grid-cols-2 gap-5 p-5">
        <%= render TextFieldComponent.new(form: f, field_name: :name, error_message: user.errors.messages[:name]) %>
        <%= render TextFieldComponent.new(form: f, field_name: :role, error_message: user.errors.messages[:role]) %>
      </section>

      <section class="grid grid-cols-1 gap-5 p-5">
        <%= render TextFieldComponent.new(form: f, field_name: :email, error_message: user.errors.messages[:email]) %>
      </section>
    </section>

    <%= render ButtonComponent.new(form: f, label: 'Salvar') %>
  <% end %>
<% end %>

app/views/admin/users/index.html.erb
<div class="flex justify-end">
  <button onclick="document.getElementById('new_user').showModal();" class="btn bg-secondary text-white hover:text-white">
    Cadastrar
  </button>
</div>

<div class="grid grid-cols-12">
  <div class="col-start-1 col-span-12">
    <div class="overflow-x-auto font-jost">
      <table class="table">
        <thead class="max-[768px]:text-[0.60rem]">
          <tr>
            <th>Nome</th>
            <th class="max-[768px]:hidden">E-mail</th>
            <th>Ações</th>
          </tr>
        </thead>

        <tbody class="max-[768px]:text-[0.60rem]">
          <% @users.each do |user| %>
            <tr>
              <td>
                <div class="flex items-center gap-3">
                  <div class="avatar">
                    <div class="w-12 h-12 flex items-center justify-center rounded-full ring ring-dsop-opaque-gray ring-offset-base-100 ring-offset-2 bg-dsop-high-light-gray">
                      <div class="flex w-full h-full items-center justify-center">
                        <div id='preview' data-action="click->upload#openFileInput">
                          <% if user.image.present? %>
                            <%= image_tag(user.image, class: "mask mask-squircle h-12 w-12") %>
                          <% else %>
                            <span class="material-symbols-outlined">add_photo_alternate </span>
                          <% end %>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div>
                    <div class=""><%= user.name %></div>
                    <div class="text-sm opacity-50"><%= user.role %></div>
                  </div>
                </div>
              </td>

              <td class="max-[768px]:hidden"><%= user.email %></td>

              <td>
                <button onclick="document.getElementById('edit_user<%= user.id %>').showModal();" title="Editar" class="p-2 rounded-full">
                  <span class="material-symbols-outlined">edit</span>
                </button>

                <dialog id="edit_user<%= user.id %>" class="modal modal-bottom sm:modal-middle">
                  <div class="modal-box">
                    <form method="dialog">
                      <button class="btn btn-sm btn-circle btn-ghost absolute right-2 top-2">✕</button>
                    </form>

                    <h3 class="text-lg">Editar Usuário</h3>

                    <%= render "form", user: user %>
                  </div>
                </dialog>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div class="flex items-center justify-center <%= 'border-t border-b' if @pagy.pages > 1 %> p-2">
  <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
</div>

<dialog id="new_user" class="modal modal-bottom sm:modal-middle">
  <div class="modal-box">
    <form method="dialog">
      <button class="btn btn-sm btn-circle btn-ghost absolute right-2 top-2">✕</button>
    </form>

    <h3 class="text-lg">Cadastrar Usuário</h3>
    <%= render "form", user: @user %>
  </div>
</dialog>